logging:
  level:
    ROOT: debug
    com.mnp.store: debug

server:
  port: 8080

spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/temp?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false
