logging:
  level:
    ROOT: debug
    com.mnp.store: debug

server:
  port: 8080

spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:file:./target/h2db/db/mnpstore;DB_CLOSE_DELAY=-1
    username: MnpStore
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    url: jdbc:h2:file:./target/h2db/db/mnpstore
    user: MnpStore
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true